# Generated by Django 4.2.7 on 2023-11-18 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerimage',
            name='picture_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
