# Generated by Django 4.2.7 on 2023-11-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0002_cornerimage_picture_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornerimage',
            name='picture_id',
        ),
    ]
