# Generated by Django 4.2.7 on 2023-11-18 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0003_remove_cornerimage_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerimage',
            name='picture_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True),
        ),
    ]
