# Generated by Django 4.2.7 on 2023-11-18 14:44

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    CornerImage = apps.get_model("corner_detect", "CornerImage")
    for row in CornerImage.objects.all():
        row.picture_id = uuid.uuid4()
        print("setting", row.picture_id, "on", row.pk)
        row.save(update_fields=["picture_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0004_cornerimage_picture_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
