# Generated by Django 4.2.7 on 2023-11-18 14:44

from django.db import migrations, models
import uuid



class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0005_auto_20231118_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornerimage',
            name='picture_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
