# Generated by Django 4.2.7 on 2023-11-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0006_auto_20231118_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornerimage',
            name='picture_id',
        ),
    ]
