# Generated by Django 4.2.7 on 2023-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0009_alter_cornerimage_picture_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
