# Generated by Django 4.2.7 on 2023-11-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0011_pricetable_cornerimage_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornerimage',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
