# Generated by Django 4.2.7 on 2023-12-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0013_locationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='barcode_num',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
