# Generated by Django 4.2.7 on 2023-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0014_pricetable_barcode_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='qr_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
