# Generated by Django 4.2.7 on 2023-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_detect', '0015_pricetable_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
